### PR TITLE
TEST: add unit test for docstrings

### PR DESCRIPTION
**Pull request by j-ittner**
The new `DocValidator` class performs wide-ranging tests of class documentation and type annotations.

To pass validation, the following must be in place:

- docstrings in place for all classes, methods, and functions
- all parameters documented in function docstrings, return value documented except when return type is `None`
- all functions with complete type hints for parameters and the return value

### CODE REVIEW

**Review by joerg-schneider — DISMISSED** [review]
Looks good, valuable addition to the tests!

**Comment by joerg-schneider** [comment]
This merges into 1.1.x – can we change to something like `dev/1.1.0rc0` to adopt new conventions? We can create `dev/1.1.0rc0` as a direct branch from `1.1.x`

**Comment by j-ittner** [comment]
> This merges into 1.1.x – can we change to something like `dev/1.1.0rc0` to adopt new conventions? We can create `dev/1.1.0rc0` as a direct branch from `1.1.x`

Done!

**Comment by j-ittner** [comment]
> > This merges into 1.1.x – can we change to something like `dev/1.1.0rc0` to adopt new conventions? We can create `dev/1.1.0rc0` as a direct branch from `1.1.x`
> 
> Done!

Changed it back as just discussed, could you please review/approve? Thanks!

**Review by joerg-schneider — APPROVED** [review]

**Pull request merged**
